[package]
name = "macro-test"
version = "0.1.0"
authors = [""]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = []

[dependencies]
btr-macros = { path = "../btr_macros" }
cosmwasm-std = { package = "secret-cosmwasm-std", version = "1.0.0" }
better-secret-math = { path = "../secret_math" }
