[package]
name = "better-secret-math"
version = "0.1.0"
authors = ["hoomp <flammable.shower939@anonaddy.me>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[[bench]]
name = "bench_main"
harness = false

[features]
default = []

[dependencies]
# Core
cosmwasm-std = { package = "secret-cosmwasm-std", version = "1.0.0" }
cosmwasm-schema = "1.1.5"
schemars = "0.8.9"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
serde_json = "1"
borsh = "0.9.3"
thiserror = "1.0"
ethnum = { git = "https://github.com/securesecrets/ethnum-rs", tag = "0.2.0", features = ["cosmwasm"] }

paste = "1.0"
derive-from-ext = "0.2"
btr-macros = { path = "../btr_macros" }

[dev-dependencies]
rstest = "0.15.0"
criterion = "0.3"
